#!/bin/bash

options=$(echo -e "  Poweroff\n  Restart\nSuspend\n  Exit i3")

selected_option=$(echo -e "$options" \
    | rofi -location 3 \
           -theme-str 'window {width: 200;} listview {lines: 4;}' \
           -yoffset 50 -xoffset -10 \
           -dmenu -i -mesg "Leaving already?")

case $selected_option in
    "  Poweroff")
        notify-send " Shutting down..."
        loginctl poweroff;;
    "  Restart")
        notify-send " Rebooting..."
        loginctl reboot;;
    "Suspend")
        notify-send " Suspending..."
        loginctl suspend;;
    "  Exit i3")
        i3-msg exit;;
esac
